import json
import httpx
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from .. import schemas, models
from ..config import settings
from ..database import get_db
from app.utils import oauth2

router = APIRouter(prefix="/ai", tags=["AI"])


async def _call_ai_api(system_prompt: str, user_prompt: str) -> dict:
    """
    Helper to call the OpenAI-compatible completions API configured in settings.ai_url.
    Parses the response and returns it as a dictionary.
    """
    payload = {
        "model": "qwen2.5:3b",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.2
    }
    
    async with httpx.AsyncClient() as client:
        # settings.ai_url is configured from the .env file
        response = await client.post(
            settings.ai_url,
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=30.0
        )
        if response.status_code != 200:
            raise HTTPException(status_code=502, detail=f"AI API error: {response.text}")
        
        result = response.json()
        content = result["choices"][0]["message"]["content"].strip()
        
        # Strip markdown code blocks if the AI outputs them
        if content.startswith("```"):
            lines = content.splitlines()
            if lines[0].startswith("```json") or lines[0].startswith("```"):
                content = "\n".join(lines[1:-1])
            else:
                content = "\n".join(lines[1:])
        
        return json.loads(content)


def _map_ai_recipe_to_raw_data(ai_data: dict) -> dict:
    """
    Converts JSON output from the AI into Spoonacular-compatible structure for the database.
    """
    ingredients_list = ai_data.get("ingredients", [])
    extended_ingredients = []
    for ing in ingredients_list:
        extended_ingredients.append({
            "id": hash(ing) % 1000000,
            "name": ing,
            "original": ing,
            "amount": 1.0,
            "unit": ""
        })
        
    instructions_raw = ai_data.get("instructions", [])
    if isinstance(instructions_raw, list):
        instructions_html = "<ol>" + "".join([f"<li>{step}</li>" for step in instructions_raw]) + "</ol>"
    else:
        instructions_html = str(instructions_raw)
        
    return {
        "title": ai_data.get("title", "AI Recipe"),
        "image": "",  # No image generated by local AI
        "extendedIngredients": extended_ingredients,
        "instructions": instructions_html,
        "readyInMinutes": 30,
        "servings": ai_data.get("servings", 4),
        "likes": 0,
        "usedIngredientCount": len(extended_ingredients),
        "usedIngredients": extended_ingredients,
        "missedIngredientCount": 0,
        "missedIngredients": [],
        "unusedIngredients": []
    }


async def generate_recipe_with_ai(ingredients_str: str, user_id: int, db: AsyncSession) -> models.Recipe:
    """
    Generates a recipe from scratch using the AI based on the user's available ingredients.
    Saves the new recipe to the database, linked to the user.
    """
    system_prompt = "Perform TASK 1: Generate a recipe from scratch using the ingredients provided."
    
    user_prompt = f"Ingredients available: {ingredients_str}"
    ai_data = await _call_ai_api(system_prompt, user_prompt)
    
    # Map raw data to match DB/Spoonacular style structure
    raw_data = _map_ai_recipe_to_raw_data(ai_data)
    
    # Create the Recipe database record
    db_recipe = models.Recipe(
        title=raw_data["title"],
        raw_data=raw_data,
        user_id=user_id
    )
    db.add(db_recipe)
    await db.commit()
    await db.refresh(db_recipe)
    
    # Add generated primary key id to raw_data for UI usage
    raw_data["id"] = db_recipe.id
    db_recipe.raw_data = raw_data
    await db.commit()
    
    return db_recipe


async def substitute_ingredient_with_ai(recipe_id: int, ingredient_to_replace: str, user_id: int, db: AsyncSession) -> models.Recipe:
    """
    Adapts an existing recipe using AI, substituting a specific ingredient with a suitable alternative.
    Saves the adapted recipe as a new recipe in the database linked to the user.
    """
    stmt = select(models.Recipe).filter((models.Recipe.id == recipe_id) | (models.Recipe.spoonacular_id == recipe_id))
    result = await db.execute(stmt)
    orig_recipe = result.scalars().first()
    
    if not orig_recipe:
        raise HTTPException(status_code=404, detail="Original recipe not found")
        
    orig_title = orig_recipe.title
    orig_ingredients = []
    if orig_recipe.raw_data and "extendedIngredients" in orig_recipe.raw_data:
        orig_ingredients = [ing.get("original", ing.get("name", "")) for ing in orig_recipe.raw_data["extendedIngredients"]]
    
    orig_instructions = orig_recipe.raw_data.get("instructions", "") if orig_recipe.raw_data else ""

    system_prompt = "Perform TASK 2: Adapt the recipe by substituting the specified ingredient."

    user_prompt = f"""Original Recipe Title: {orig_title}
Original Ingredients: {json.dumps(orig_ingredients)}
Original Instructions: {orig_instructions}
Ingredient to Replace: {ingredient_to_replace}"""

    ai_data = await _call_ai_api(system_prompt, user_prompt)
    
    # Map raw data to match DB/Spoonacular style structure
    raw_data = _map_ai_recipe_to_raw_data(ai_data)
    
    # Save as new custom recipe for the user
    db_recipe = models.Recipe(
        title=raw_data["title"],
        raw_data=raw_data,
        user_id=user_id
    )
    db.add(db_recipe)
    await db.commit()
    await db.refresh(db_recipe)
    
    # Add generated primary key id to raw_data for UI usage
    raw_data["id"] = db_recipe.id
    db_recipe.raw_data = raw_data
    await db.commit()
    
    return db_recipe


@router.post("/generate", response_model=dict)
async def generate_recipe_ai(
    req: schemas.AIRecipeGenerateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(oauth2.get_current_user)
):
    """Generate a custom recipe from ingredients using AI and save it to the DB."""
    db_recipe = await generate_recipe_with_ai(req.ingredients, current_user.id, db)
    return {"id": db_recipe.id, "title": db_recipe.title}


@router.post("/substitute/{recipe_id}", response_model=dict)
async def substitute_recipe_ai(
    recipe_id: int,
    req: schemas.AIRecipeSubstituteRequest,
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(oauth2.get_current_user)
):
    """Adapt an existing recipe using AI by replacing a specific ingredient, saving the new version to DB."""
    db_recipe = await substitute_ingredient_with_ai(recipe_id, req.ingredient_to_replace, current_user.id, db)
    return {"id": db_recipe.id, "title": db_recipe.title}


async def get_quick_substitute_from_ai(recipe_id: int, ingredient_to_replace: str, db: AsyncSession) -> str:
    """
    Asks the AI for a quick, 1-2 sentence substitute recommendation for a specific ingredient in a recipe.
    """
    stmt = select(models.Recipe).filter((models.Recipe.id == recipe_id) | (models.Recipe.spoonacular_id == recipe_id))
    result = await db.execute(stmt)
    orig_recipe = result.scalars().first()
    
    recipe_title = orig_recipe.title if orig_recipe else "Recipe"
    
    system_prompt = "Provide a quick 1-2 sentence substitution suggestion directly as text (do not output JSON)."

    user_prompt = f"Recipe: {recipe_title}\nIngredient to replace: {ingredient_to_replace}"
    
    payload = {
        "model": "qwen2.5:3b",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.5
    }
    
    async with httpx.AsyncClient() as client:
        response = await client.post(
            settings.ai_url,
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=25.0
        )
        if response.status_code != 200:
            raise HTTPException(status_code=502, detail=f"AI API error: {response.text}")
        
        result = response.json()
        recommendation = result["choices"][0]["message"]["content"].strip()
        return recommendation


@router.get("/quick-substitute", response_model=dict)
async def quick_substitute_ai(
    recipe_id: int,
    ingredient: str,
    db: AsyncSession = Depends(get_db)
):
    """Get a quick substitute recommendation from the AI for an ingredient."""
    recommendation = await get_quick_substitute_from_ai(recipe_id, ingredient, db)
    return {"recommendation": recommendation}